name: Unity CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
#      - name: Run tests
#        uses: game-ci/unity-test-runner@v2
#        env:
#          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#        with:
#          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Set Unity Bundle version from tag
      - name: Set Unity Version
        run: |
          # Extract tag name
          TAG=${GITHUB_REF#refs/tags/}

          # Strip leading 'v' if present
          VERSION=${TAG#v}

          # Remove any pre-release suffix (e.g., -beta1, -alpha2)
          VERSION=${VERSION%%-*}

          echo "Setting Unity BundleVersion to $VERSION"

          # Apply to ProjectSettings.asset
          sed -i "s/m_BundleVersion:.*/m_BundleVersion: $VERSION/" ProjectSettings/ProjectSettings.asset

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4.5.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customImage: 'unityci/editor:ubuntu-6000.0.58f1-windows-mono-3.1.0'
          allowDirtyBuild: true
          targetPlatform: StandaloneWindows64
          buildName: HNode
          buildsPath: Builds

      # Output
      - name: Upload Windows Portable Build
        uses: actions/upload-artifact@v4
        with:
          name: Windows Portable Build
          path: Builds

      # Get nsis
      - name: Install NSIS
        run: |
          sudo apt-get -y update
          sudo apt-get -y install nsis

      # run NSIS installer script for windows builds
      - name: NSIS Installer
        uses: joncloud/makensis-action@v4.1
        with:
          script-file: .github/scripts/installer.nsi

      # Upload installer
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: Windows Installer
          path: .github/scripts/HNode setup.exe
